spring:
  application:
    name: dasnSimei
  datasource:
    password: 22360512
    url: jdbc:mysql://localhost:3306/springboot
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false